package com.dao.core.checkmis;

import com.api.dto.ApiGzjlDto;
import com.biz.dto.gzrw.GzrwDto;
import com.core.model.checkmis.Gzrw;
import com.core.model.checkmis.GzrwExample;
import java.util.List;

import com.core.pageModel.PageHelper;
import org.apache.ibatis.annotations.Param;

public interface GzrwMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    long countByExample(GzrwExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int deleteByExample(GzrwExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int insert(Gzrw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int insertSelective(Gzrw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    List<Gzrw> selectByExample(GzrwExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    Gzrw selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gzrw record, @Param("example") GzrwExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gzrw record, @Param("example") GzrwExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gzrw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gzrw record);

    List<Gzrw> selectValidRwList(@Param("q") GzrwDto gzrw, @Param("page")PageHelper pageHelper);

    List<ApiGzjlDto> selectAppGzjlList();
}