package com.dao.core.checkmis;

import com.core.model.checkmis.Unit;
import com.core.model.checkmis.UnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    long countByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int deleteByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    List<Unit> selectByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    Unit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_UNIT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Unit record);
}