package com.dao.core.checkmis;

import com.core.model.checkmis.ST_WTXD_DMB;
import com.core.model.checkmis.ST_WTXD_DMBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ST_WTXD_DMBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    long countByExample(ST_WTXD_DMBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int deleteByExample(ST_WTXD_DMBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int insert(ST_WTXD_DMB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int insertSelective(ST_WTXD_DMB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    List<ST_WTXD_DMB> selectByExample(ST_WTXD_DMBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    ST_WTXD_DMB selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ST_WTXD_DMB record, @Param("example") ST_WTXD_DMBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ST_WTXD_DMB record, @Param("example") ST_WTXD_DMBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ST_WTXD_DMB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_WTXD_DMB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ST_WTXD_DMB record);
}