package com.dao.core.checkmis;

import com.core.model.checkmis.Gzjlsc;
import com.core.model.checkmis.GzjlscExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GzjlscMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    long countByExample(GzjlscExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    int deleteByExample(GzjlscExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    int insert(Gzjlsc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    int insertSelective(Gzjlsc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    List<Gzjlsc> selectByExample(GzjlscExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") Gzjlsc record, @Param("example") GzjlscExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    int updateByExample(@Param("record") Gzjlsc record, @Param("example") GzjlscExample example);
}