package com.dao.core.checkmis;

import com.biz.dto.gzrw.GzrwxzcyDto;
import com.core.model.checkmis.Gzrwxzcy;
import com.core.model.checkmis.GzrwxzcyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GzrwxzcyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    long countByExample(GzrwxzcyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int deleteByExample(GzrwxzcyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int insert(Gzrwxzcy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int insertSelective(Gzrwxzcy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    List<Gzrwxzcy> selectByExample(GzrwxzcyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    Gzrwxzcy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gzrwxzcy record, @Param("example") GzrwxzcyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gzrwxzcy record, @Param("example") GzrwxzcyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gzrwxzcy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRWXZCY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gzrwxzcy record);

    List<GzrwxzcyDto> selectAppRwList(GzrwxzcyDto gzrwxzcyDto);
}