package com.dao.core.checkmis;

import com.core.model.checkmis.Gzjlmx;
import com.core.model.checkmis.GzjlmxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GzjlmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    long countByExample(GzjlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int deleteByExample(GzjlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int insert(Gzjlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int insertSelective(Gzjlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    List<Gzjlmx> selectByExample(GzjlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    Gzjlmx selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gzjlmx record, @Param("example") GzjlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gzjlmx record, @Param("example") GzjlmxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gzjlmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gzjlmx record);
}