package com.dao.core.checkmis;

import com.core.model.checkmis.Gzjljclc;
import com.core.model.checkmis.GzjljclcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GzjljclcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    long countByExample(GzjljclcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int deleteByExample(GzjljclcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int insert(Gzjljclc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int insertSelective(Gzjljclc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    List<Gzjljclc> selectByExample(GzjljclcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    Gzjljclc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gzjljclc record, @Param("example") GzjljclcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gzjljclc record, @Param("example") GzjljclcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gzjljclc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gzjljclc record);
}