package com.dao.core.checkmis;

import com.biz.dto.gzxs.GzxsRqktzsDto;
import com.core.model.checkmis.GzxsRqktzs;
import com.core.model.checkmis.GzxsRqktzsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GzxsRqktzsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int countByExample(GzxsRqktzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int deleteByExample(GzxsRqktzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int insert(GzxsRqktzs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int insertSelective(GzxsRqktzs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    List<GzxsRqktzs> selectByExample(GzxsRqktzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    GzxsRqktzs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") GzxsRqktzs record, @Param("example") GzxsRqktzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByExample(@Param("record") GzxsRqktzs record, @Param("example") GzxsRqktzsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByPrimaryKeySelective(GzxsRqktzs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_RQKTZS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByPrimaryKey(GzxsRqktzs record);

    List<GzxsRqktzsDto> selectDetailByExample(GzxsRqktzsExample example);
}