package com.dao.core.checkmis;

import com.biz.dto.gzjlsc.GzxsGroupDto;
import com.core.model.checkmis.Gzxs;
import com.core.model.checkmis.GzxsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GzxsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int countByExample(GzxsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int deleteByExample(GzxsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int insert(Gzxs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int insertSelective(Gzxs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    List<Gzxs> selectByExample(GzxsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    Gzxs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Gzxs record, @Param("example") GzxsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByExample(@Param("record") Gzxs record, @Param("example") GzxsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByPrimaryKeySelective(Gzxs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByPrimaryKey(Gzxs record);

    List<GzxsGroupDto> groupList(GzxsExample example);
}