package com.dao.core.checkmis;

import com.biz.dto.gzxs.GzxsJcqkbMxDto;
import com.core.model.checkmis.GzxsJcqkbMx;
import com.core.model.checkmis.GzxsJcqkbMxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GzxsJcqkbMxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    long countByExample(GzxsJcqkbMxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    int deleteByExample(GzxsJcqkbMxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    int insert(GzxsJcqkbMx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    int insertSelective(GzxsJcqkbMx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    List<GzxsJcqkbMx> selectByExample(GzxsJcqkbMxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") GzxsJcqkbMx record, @Param("example") GzxsJcqkbMxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JCQKB_MX
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    int updateByExample(@Param("record") GzxsJcqkbMx record, @Param("example") GzxsJcqkbMxExample example);

    List<GzxsJcqkbMxDto> selectDetail(@Param("jcqkbId") Long jcqkbId);
}