package com.dao.core.checkmis;

import com.core.model.checkmis.LqsknrflDmb;
import com.core.model.checkmis.LqsknrflDmbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LqsknrflDmbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    long countByExample(LqsknrflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int deleteByExample(LqsknrflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int insert(LqsknrflDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int insertSelective(LqsknrflDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    List<LqsknrflDmb> selectByExample(LqsknrflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    LqsknrflDmb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LqsknrflDmb record, @Param("example") LqsknrflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LqsknrflDmb record, @Param("example") LqsknrflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LqsknrflDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_LQSKNRFL_DMB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LqsknrflDmb record);
}