package com.dao.core.checkmis;

import com.core.model.checkmis.ZzdwZdMap;
import com.core.model.checkmis.ZzdwZdMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZzdwZdMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    long countByExample(ZzdwZdMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    int deleteByExample(ZzdwZdMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    int insert(ZzdwZdMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    int insertSelective(ZzdwZdMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    List<ZzdwZdMap> selectByExample(ZzdwZdMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZzdwZdMap record, @Param("example") ZzdwZdMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_ZD_MAP
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZzdwZdMap record, @Param("example") ZzdwZdMapExample example);
}