package com.dao.core.checkmis;

import com.core.model.checkmis.ZzdwDmb;
import com.core.model.checkmis.ZzdwDmbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZzdwDmbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    long countByExample(ZzdwDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int deleteByExample(ZzdwDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int insert(ZzdwDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int insertSelective(ZzdwDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    List<ZzdwDmb> selectByExample(ZzdwDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    ZzdwDmb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZzdwDmb record, @Param("example") ZzdwDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZzdwDmb record, @Param("example") ZzdwDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZzdwDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_ZZDW_DMB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZzdwDmb record);
}