package com.dao.core.checkmis;

import com.core.model.checkmis.GzxsJtwt;
import com.core.model.checkmis.GzxsJtwtExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GzxsJtwtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int countByExample(GzxsJtwtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int deleteByExample(GzxsJtwtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int insert(GzxsJtwt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int insertSelective(GzxsJtwt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    List<GzxsJtwt> selectByExample(GzxsJtwtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    GzxsJtwt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") GzxsJtwt record, @Param("example") GzxsJtwtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByExample(@Param("record") GzxsJtwt record, @Param("example") GzxsJtwtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByPrimaryKeySelective(GzxsJtwt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS_JTWT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    int updateByPrimaryKey(GzxsJtwt record);
}