package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzjljclcExample extends PageHelper {
    /**
     * 数据库:CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * 数据库:CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * 数据库:CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public GzjljclcExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdIsNull() {
            addCriterion("GZJLMX_ID is null");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdIsNotNull() {
            addCriterion("GZJLMX_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdEqualTo(Long value) {
            addCriterion("GZJLMX_ID =", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdNotEqualTo(Long value) {
            addCriterion("GZJLMX_ID <>", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdGreaterThan(Long value) {
            addCriterion("GZJLMX_ID >", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GZJLMX_ID >=", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdLessThan(Long value) {
            addCriterion("GZJLMX_ID <", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdLessThanOrEqualTo(Long value) {
            addCriterion("GZJLMX_ID <=", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdIn(List<Long> values) {
            addCriterion("GZJLMX_ID in", values, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdNotIn(List<Long> values) {
            addCriterion("GZJLMX_ID not in", values, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdBetween(Long value1, Long value2) {
            addCriterion("GZJLMX_ID between", value1, value2, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdNotBetween(Long value1, Long value2) {
            addCriterion("GZJLMX_ID not between", value1, value2, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andJcccIsNull() {
            addCriterion("JCCC is null");
            return (Criteria) this;
        }

        public Criteria andJcccIsNotNull() {
            addCriterion("JCCC is not null");
            return (Criteria) this;
        }

        public Criteria andJcccEqualTo(String value) {
            addCriterion("JCCC =", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccNotEqualTo(String value) {
            addCriterion("JCCC <>", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccGreaterThan(String value) {
            addCriterion("JCCC >", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccGreaterThanOrEqualTo(String value) {
            addCriterion("JCCC >=", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccLessThan(String value) {
            addCriterion("JCCC <", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccLessThanOrEqualTo(String value) {
            addCriterion("JCCC <=", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccLike(String value) {
            addCriterion("JCCC like", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccNotLike(String value) {
            addCriterion("JCCC not like", value, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccIn(List<String> values) {
            addCriterion("JCCC in", values, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccNotIn(List<String> values) {
            addCriterion("JCCC not in", values, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccBetween(String value1, String value2) {
            addCriterion("JCCC between", value1, value2, "jccc");
            return (Criteria) this;
        }

        public Criteria andJcccNotBetween(String value1, String value2) {
            addCriterion("JCCC not between", value1, value2, "jccc");
            return (Criteria) this;
        }

        public Criteria andDddIsNull() {
            addCriterion("DDD is null");
            return (Criteria) this;
        }

        public Criteria andDddIsNotNull() {
            addCriterion("DDD is not null");
            return (Criteria) this;
        }

        public Criteria andDddEqualTo(String value) {
            addCriterion("DDD =", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddNotEqualTo(String value) {
            addCriterion("DDD <>", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddGreaterThan(String value) {
            addCriterion("DDD >", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddGreaterThanOrEqualTo(String value) {
            addCriterion("DDD >=", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddLessThan(String value) {
            addCriterion("DDD <", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddLessThanOrEqualTo(String value) {
            addCriterion("DDD <=", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddLike(String value) {
            addCriterion("DDD like", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddNotLike(String value) {
            addCriterion("DDD not like", value, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddIn(List<String> values) {
            addCriterion("DDD in", values, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddNotIn(List<String> values) {
            addCriterion("DDD not in", values, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddBetween(String value1, String value2) {
            addCriterion("DDD between", value1, value2, "ddd");
            return (Criteria) this;
        }

        public Criteria andDddNotBetween(String value1, String value2) {
            addCriterion("DDD not between", value1, value2, "ddd");
            return (Criteria) this;
        }

        public Criteria andQdIsNull() {
            addCriterion("QD is null");
            return (Criteria) this;
        }

        public Criteria andQdIsNotNull() {
            addCriterion("QD is not null");
            return (Criteria) this;
        }

        public Criteria andQdEqualTo(String value) {
            addCriterion("QD =", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdNotEqualTo(String value) {
            addCriterion("QD <>", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdGreaterThan(String value) {
            addCriterion("QD >", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdGreaterThanOrEqualTo(String value) {
            addCriterion("QD >=", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdLessThan(String value) {
            addCriterion("QD <", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdLessThanOrEqualTo(String value) {
            addCriterion("QD <=", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdLike(String value) {
            addCriterion("QD like", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdNotLike(String value) {
            addCriterion("QD not like", value, "qd");
            return (Criteria) this;
        }

        public Criteria andQdIn(List<String> values) {
            addCriterion("QD in", values, "qd");
            return (Criteria) this;
        }

        public Criteria andQdNotIn(List<String> values) {
            addCriterion("QD not in", values, "qd");
            return (Criteria) this;
        }

        public Criteria andQdBetween(String value1, String value2) {
            addCriterion("QD between", value1, value2, "qd");
            return (Criteria) this;
        }

        public Criteria andQdNotBetween(String value1, String value2) {
            addCriterion("QD not between", value1, value2, "qd");
            return (Criteria) this;
        }

        public Criteria andJclcKssjIsNull() {
            addCriterion("JCLC_KSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJclcKssjIsNotNull() {
            addCriterion("JCLC_KSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJclcKssjEqualTo(Date value) {
            addCriterion("JCLC_KSSJ =", value, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjNotEqualTo(Date value) {
            addCriterion("JCLC_KSSJ <>", value, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjGreaterThan(Date value) {
            addCriterion("JCLC_KSSJ >", value, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JCLC_KSSJ >=", value, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjLessThan(Date value) {
            addCriterion("JCLC_KSSJ <", value, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjLessThanOrEqualTo(Date value) {
            addCriterion("JCLC_KSSJ <=", value, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjIn(List<Date> values) {
            addCriterion("JCLC_KSSJ in", values, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjNotIn(List<Date> values) {
            addCriterion("JCLC_KSSJ not in", values, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjBetween(Date value1, Date value2) {
            addCriterion("JCLC_KSSJ between", value1, value2, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcKssjNotBetween(Date value1, Date value2) {
            addCriterion("JCLC_KSSJ not between", value1, value2, "jclcKssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjIsNull() {
            addCriterion("JCLC_JSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJclcJssjIsNotNull() {
            addCriterion("JCLC_JSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJclcJssjEqualTo(Date value) {
            addCriterion("JCLC_JSSJ =", value, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjNotEqualTo(Date value) {
            addCriterion("JCLC_JSSJ <>", value, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjGreaterThan(Date value) {
            addCriterion("JCLC_JSSJ >", value, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JCLC_JSSJ >=", value, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjLessThan(Date value) {
            addCriterion("JCLC_JSSJ <", value, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjLessThanOrEqualTo(Date value) {
            addCriterion("JCLC_JSSJ <=", value, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjIn(List<Date> values) {
            addCriterion("JCLC_JSSJ in", values, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjNotIn(List<Date> values) {
            addCriterion("JCLC_JSSJ not in", values, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjBetween(Date value1, Date value2) {
            addCriterion("JCLC_JSSJ between", value1, value2, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andJclcJssjNotBetween(Date value1, Date value2) {
            addCriterion("JCLC_JSSJ not between", value1, value2, "jclcJssj");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL_JCLC
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}