package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzjlExample extends PageHelper {
    /**
     * 数据库:CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * 数据库:CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * 数据库:CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public GzjlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGzrwIdIsNull() {
            addCriterion("GZRW_ID is null");
            return (Criteria) this;
        }

        public Criteria andGzrwIdIsNotNull() {
            addCriterion("GZRW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGzrwIdEqualTo(Long value) {
            addCriterion("GZRW_ID =", value, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdNotEqualTo(Long value) {
            addCriterion("GZRW_ID <>", value, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdGreaterThan(Long value) {
            addCriterion("GZRW_ID >", value, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GZRW_ID >=", value, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdLessThan(Long value) {
            addCriterion("GZRW_ID <", value, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdLessThanOrEqualTo(Long value) {
            addCriterion("GZRW_ID <=", value, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdIn(List<Long> values) {
            addCriterion("GZRW_ID in", values, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdNotIn(List<Long> values) {
            addCriterion("GZRW_ID not in", values, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdBetween(Long value1, Long value2) {
            addCriterion("GZRW_ID between", value1, value2, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andGzrwIdNotBetween(Long value1, Long value2) {
            addCriterion("GZRW_ID not between", value1, value2, "gzrwId");
            return (Criteria) this;
        }

        public Criteria andJhbhIsNull() {
            addCriterion("JHBH is null");
            return (Criteria) this;
        }

        public Criteria andJhbhIsNotNull() {
            addCriterion("JHBH is not null");
            return (Criteria) this;
        }

        public Criteria andJhbhEqualTo(String value) {
            addCriterion("JHBH =", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhNotEqualTo(String value) {
            addCriterion("JHBH <>", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhGreaterThan(String value) {
            addCriterion("JHBH >", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhGreaterThanOrEqualTo(String value) {
            addCriterion("JHBH >=", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhLessThan(String value) {
            addCriterion("JHBH <", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhLessThanOrEqualTo(String value) {
            addCriterion("JHBH <=", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhLike(String value) {
            addCriterion("JHBH like", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhNotLike(String value) {
            addCriterion("JHBH not like", value, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhIn(List<String> values) {
            addCriterion("JHBH in", values, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhNotIn(List<String> values) {
            addCriterion("JHBH not in", values, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhBetween(String value1, String value2) {
            addCriterion("JHBH between", value1, value2, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhbhNotBetween(String value1, String value2) {
            addCriterion("JHBH not between", value1, value2, "jhbh");
            return (Criteria) this;
        }

        public Criteria andJhmcIsNull() {
            addCriterion("JHMC is null");
            return (Criteria) this;
        }

        public Criteria andJhmcIsNotNull() {
            addCriterion("JHMC is not null");
            return (Criteria) this;
        }

        public Criteria andJhmcEqualTo(String value) {
            addCriterion("JHMC =", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcNotEqualTo(String value) {
            addCriterion("JHMC <>", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcGreaterThan(String value) {
            addCriterion("JHMC >", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcGreaterThanOrEqualTo(String value) {
            addCriterion("JHMC >=", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcLessThan(String value) {
            addCriterion("JHMC <", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcLessThanOrEqualTo(String value) {
            addCriterion("JHMC <=", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcLike(String value) {
            addCriterion("JHMC like", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcNotLike(String value) {
            addCriterion("JHMC not like", value, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcIn(List<String> values) {
            addCriterion("JHMC in", values, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcNotIn(List<String> values) {
            addCriterion("JHMC not in", values, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcBetween(String value1, String value2) {
            addCriterion("JHMC between", value1, value2, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhmcNotBetween(String value1, String value2) {
            addCriterion("JHMC not between", value1, value2, "jhmc");
            return (Criteria) this;
        }

        public Criteria andJhkssjIsNull() {
            addCriterion("JHKSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJhkssjIsNotNull() {
            addCriterion("JHKSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJhkssjEqualTo(Date value) {
            addCriterion("JHKSSJ =", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotEqualTo(Date value) {
            addCriterion("JHKSSJ <>", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjGreaterThan(Date value) {
            addCriterion("JHKSSJ >", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JHKSSJ >=", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjLessThan(Date value) {
            addCriterion("JHKSSJ <", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjLessThanOrEqualTo(Date value) {
            addCriterion("JHKSSJ <=", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjIn(List<Date> values) {
            addCriterion("JHKSSJ in", values, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotIn(List<Date> values) {
            addCriterion("JHKSSJ not in", values, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjBetween(Date value1, Date value2) {
            addCriterion("JHKSSJ between", value1, value2, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotBetween(Date value1, Date value2) {
            addCriterion("JHKSSJ not between", value1, value2, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjIsNull() {
            addCriterion("JHJSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJhjssjIsNotNull() {
            addCriterion("JHJSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJhjssjEqualTo(Date value) {
            addCriterion("JHJSSJ =", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotEqualTo(Date value) {
            addCriterion("JHJSSJ <>", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjGreaterThan(Date value) {
            addCriterion("JHJSSJ >", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JHJSSJ >=", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjLessThan(Date value) {
            addCriterion("JHJSSJ <", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjLessThanOrEqualTo(Date value) {
            addCriterion("JHJSSJ <=", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjIn(List<Date> values) {
            addCriterion("JHJSSJ in", values, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotIn(List<Date> values) {
            addCriterion("JHJSSJ not in", values, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjBetween(Date value1, Date value2) {
            addCriterion("JHJSSJ between", value1, value2, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotBetween(Date value1, Date value2) {
            addCriterion("JHJSSJ not between", value1, value2, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andTbztIsNull() {
            addCriterion("TBZT is null");
            return (Criteria) this;
        }

        public Criteria andTbztIsNotNull() {
            addCriterion("TBZT is not null");
            return (Criteria) this;
        }

        public Criteria andTbztEqualTo(Short value) {
            addCriterion("TBZT =", value, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztNotEqualTo(Short value) {
            addCriterion("TBZT <>", value, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztGreaterThan(Short value) {
            addCriterion("TBZT >", value, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztGreaterThanOrEqualTo(Short value) {
            addCriterion("TBZT >=", value, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztLessThan(Short value) {
            addCriterion("TBZT <", value, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztLessThanOrEqualTo(Short value) {
            addCriterion("TBZT <=", value, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztIn(List<Short> values) {
            addCriterion("TBZT in", values, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztNotIn(List<Short> values) {
            addCriterion("TBZT not in", values, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztBetween(Short value1, Short value2) {
            addCriterion("TBZT between", value1, value2, "tbzt");
            return (Criteria) this;
        }

        public Criteria andTbztNotBetween(Short value1, Short value2) {
            addCriterion("TBZT not between", value1, value2, "tbzt");
            return (Criteria) this;
        }

        public Criteria andShztIsNull() {
            addCriterion("SHZT is null");
            return (Criteria) this;
        }

        public Criteria andShztIsNotNull() {
            addCriterion("SHZT is not null");
            return (Criteria) this;
        }

        public Criteria andShztEqualTo(Short value) {
            addCriterion("SHZT =", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotEqualTo(Short value) {
            addCriterion("SHZT <>", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztGreaterThan(Short value) {
            addCriterion("SHZT >", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztGreaterThanOrEqualTo(Short value) {
            addCriterion("SHZT >=", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztLessThan(Short value) {
            addCriterion("SHZT <", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztLessThanOrEqualTo(Short value) {
            addCriterion("SHZT <=", value, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztIn(List<Short> values) {
            addCriterion("SHZT in", values, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotIn(List<Short> values) {
            addCriterion("SHZT not in", values, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztBetween(Short value1, Short value2) {
            addCriterion("SHZT between", value1, value2, "shzt");
            return (Criteria) this;
        }

        public Criteria andShztNotBetween(Short value1, Short value2) {
            addCriterion("SHZT not between", value1, value2, "shzt");
            return (Criteria) this;
        }

        public Criteria andJhlxIsNull() {
            addCriterion("JHLX is null");
            return (Criteria) this;
        }

        public Criteria andJhlxIsNotNull() {
            addCriterion("JHLX is not null");
            return (Criteria) this;
        }

        public Criteria andJhlxEqualTo(Short value) {
            addCriterion("JHLX =", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxNotEqualTo(Short value) {
            addCriterion("JHLX <>", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxGreaterThan(Short value) {
            addCriterion("JHLX >", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxGreaterThanOrEqualTo(Short value) {
            addCriterion("JHLX >=", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxLessThan(Short value) {
            addCriterion("JHLX <", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxLessThanOrEqualTo(Short value) {
            addCriterion("JHLX <=", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxIn(List<Short> values) {
            addCriterion("JHLX in", values, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxNotIn(List<Short> values) {
            addCriterion("JHLX not in", values, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxBetween(Short value1, Short value2) {
            addCriterion("JHLX between", value1, value2, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxNotBetween(Short value1, Short value2) {
            addCriterion("JHLX not between", value1, value2, "jhlx");
            return (Criteria) this;
        }

        public Criteria andZmIsNull() {
            addCriterion("ZM is null");
            return (Criteria) this;
        }

        public Criteria andZmIsNotNull() {
            addCriterion("ZM is not null");
            return (Criteria) this;
        }

        public Criteria andZmEqualTo(String value) {
            addCriterion("ZM =", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmNotEqualTo(String value) {
            addCriterion("ZM <>", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmGreaterThan(String value) {
            addCriterion("ZM >", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmGreaterThanOrEqualTo(String value) {
            addCriterion("ZM >=", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmLessThan(String value) {
            addCriterion("ZM <", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmLessThanOrEqualTo(String value) {
            addCriterion("ZM <=", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmLike(String value) {
            addCriterion("ZM like", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmNotLike(String value) {
            addCriterion("ZM not like", value, "zm");
            return (Criteria) this;
        }

        public Criteria andZmIn(List<String> values) {
            addCriterion("ZM in", values, "zm");
            return (Criteria) this;
        }

        public Criteria andZmNotIn(List<String> values) {
            addCriterion("ZM not in", values, "zm");
            return (Criteria) this;
        }

        public Criteria andZmBetween(String value1, String value2) {
            addCriterion("ZM between", value1, value2, "zm");
            return (Criteria) this;
        }

        public Criteria andZmNotBetween(String value1, String value2) {
            addCriterion("ZM not between", value1, value2, "zm");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andXzidIsNull() {
            addCriterion("XZID is null");
            return (Criteria) this;
        }

        public Criteria andXzidIsNotNull() {
            addCriterion("XZID is not null");
            return (Criteria) this;
        }

        public Criteria andXzidEqualTo(Long value) {
            addCriterion("XZID =", value, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidNotEqualTo(Long value) {
            addCriterion("XZID <>", value, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidGreaterThan(Long value) {
            addCriterion("XZID >", value, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidGreaterThanOrEqualTo(Long value) {
            addCriterion("XZID >=", value, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidLessThan(Long value) {
            addCriterion("XZID <", value, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidLessThanOrEqualTo(Long value) {
            addCriterion("XZID <=", value, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidIn(List<Long> values) {
            addCriterion("XZID in", values, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidNotIn(List<Long> values) {
            addCriterion("XZID not in", values, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidBetween(Long value1, Long value2) {
            addCriterion("XZID between", value1, value2, "xzid");
            return (Criteria) this;
        }

        public Criteria andXzidNotBetween(Long value1, Long value2) {
            addCriterion("XZID not between", value1, value2, "xzid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}