package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzjlJcczExample extends PageHelper {
    /**
     * 数据库:CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * 数据库:CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * 数据库:CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public GzjlJcczExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdIsNull() {
            addCriterion("GZJLMX_ID is null");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdIsNotNull() {
            addCriterion("GZJLMX_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdEqualTo(Long value) {
            addCriterion("GZJLMX_ID =", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdNotEqualTo(Long value) {
            addCriterion("GZJLMX_ID <>", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdGreaterThan(Long value) {
            addCriterion("GZJLMX_ID >", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GZJLMX_ID >=", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdLessThan(Long value) {
            addCriterion("GZJLMX_ID <", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdLessThanOrEqualTo(Long value) {
            addCriterion("GZJLMX_ID <=", value, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdIn(List<Long> values) {
            addCriterion("GZJLMX_ID in", values, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdNotIn(List<Long> values) {
            addCriterion("GZJLMX_ID not in", values, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdBetween(Long value1, Long value2) {
            addCriterion("GZJLMX_ID between", value1, value2, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andGzjlmxIdNotBetween(Long value1, Long value2) {
            addCriterion("GZJLMX_ID not between", value1, value2, "gzjlmxId");
            return (Criteria) this;
        }

        public Criteria andJcczIsNull() {
            addCriterion("JCCZ is null");
            return (Criteria) this;
        }

        public Criteria andJcczIsNotNull() {
            addCriterion("JCCZ is not null");
            return (Criteria) this;
        }

        public Criteria andJcczEqualTo(String value) {
            addCriterion("JCCZ =", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczNotEqualTo(String value) {
            addCriterion("JCCZ <>", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczGreaterThan(String value) {
            addCriterion("JCCZ >", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczGreaterThanOrEqualTo(String value) {
            addCriterion("JCCZ >=", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczLessThan(String value) {
            addCriterion("JCCZ <", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczLessThanOrEqualTo(String value) {
            addCriterion("JCCZ <=", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczLike(String value) {
            addCriterion("JCCZ like", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczNotLike(String value) {
            addCriterion("JCCZ not like", value, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczIn(List<String> values) {
            addCriterion("JCCZ in", values, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczNotIn(List<String> values) {
            addCriterion("JCCZ not in", values, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczBetween(String value1, String value2) {
            addCriterion("JCCZ between", value1, value2, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczNotBetween(String value1, String value2) {
            addCriterion("JCCZ not between", value1, value2, "jccz");
            return (Criteria) this;
        }

        public Criteria andJcczKssjIsNull() {
            addCriterion("JCCZ_KSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJcczKssjIsNotNull() {
            addCriterion("JCCZ_KSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJcczKssjEqualTo(Date value) {
            addCriterion("JCCZ_KSSJ =", value, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjNotEqualTo(Date value) {
            addCriterion("JCCZ_KSSJ <>", value, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjGreaterThan(Date value) {
            addCriterion("JCCZ_KSSJ >", value, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JCCZ_KSSJ >=", value, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjLessThan(Date value) {
            addCriterion("JCCZ_KSSJ <", value, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjLessThanOrEqualTo(Date value) {
            addCriterion("JCCZ_KSSJ <=", value, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjIn(List<Date> values) {
            addCriterion("JCCZ_KSSJ in", values, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjNotIn(List<Date> values) {
            addCriterion("JCCZ_KSSJ not in", values, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjBetween(Date value1, Date value2) {
            addCriterion("JCCZ_KSSJ between", value1, value2, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczKssjNotBetween(Date value1, Date value2) {
            addCriterion("JCCZ_KSSJ not between", value1, value2, "jcczKssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjIsNull() {
            addCriterion("JCCZ_JSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJcczJssjIsNotNull() {
            addCriterion("JCCZ_JSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJcczJssjEqualTo(Date value) {
            addCriterion("JCCZ_JSSJ =", value, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjNotEqualTo(Date value) {
            addCriterion("JCCZ_JSSJ <>", value, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjGreaterThan(Date value) {
            addCriterion("JCCZ_JSSJ >", value, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JCCZ_JSSJ >=", value, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjLessThan(Date value) {
            addCriterion("JCCZ_JSSJ <", value, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjLessThanOrEqualTo(Date value) {
            addCriterion("JCCZ_JSSJ <=", value, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjIn(List<Date> values) {
            addCriterion("JCCZ_JSSJ in", values, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjNotIn(List<Date> values) {
            addCriterion("JCCZ_JSSJ not in", values, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjBetween(Date value1, Date value2) {
            addCriterion("JCCZ_JSSJ between", value1, value2, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJcczJssjNotBetween(Date value1, Date value2) {
            addCriterion("JCCZ_JSSJ not between", value1, value2, "jcczJssj");
            return (Criteria) this;
        }

        public Criteria andJczdIsNull() {
            addCriterion("JCZD is null");
            return (Criteria) this;
        }

        public Criteria andJczdIsNotNull() {
            addCriterion("JCZD is not null");
            return (Criteria) this;
        }

        public Criteria andJczdEqualTo(String value) {
            addCriterion("JCZD =", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdNotEqualTo(String value) {
            addCriterion("JCZD <>", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdGreaterThan(String value) {
            addCriterion("JCZD >", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdGreaterThanOrEqualTo(String value) {
            addCriterion("JCZD >=", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdLessThan(String value) {
            addCriterion("JCZD <", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdLessThanOrEqualTo(String value) {
            addCriterion("JCZD <=", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdLike(String value) {
            addCriterion("JCZD like", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdNotLike(String value) {
            addCriterion("JCZD not like", value, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdIn(List<String> values) {
            addCriterion("JCZD in", values, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdNotIn(List<String> values) {
            addCriterion("JCZD not in", values, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdBetween(String value1, String value2) {
            addCriterion("JCZD between", value1, value2, "jczd");
            return (Criteria) this;
        }

        public Criteria andJczdNotBetween(String value1, String value2) {
            addCriterion("JCZD not between", value1, value2, "jczd");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJL_JCCZ
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}