package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzjlmxExample extends PageHelper {
    /**
     * 数据库:CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * 数据库:CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * 数据库:CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public GzjlmxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGzjlIdIsNull() {
            addCriterion("GZJL_ID is null");
            return (Criteria) this;
        }

        public Criteria andGzjlIdIsNotNull() {
            addCriterion("GZJL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGzjlIdEqualTo(Long value) {
            addCriterion("GZJL_ID =", value, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdNotEqualTo(Long value) {
            addCriterion("GZJL_ID <>", value, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdGreaterThan(Long value) {
            addCriterion("GZJL_ID >", value, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GZJL_ID >=", value, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdLessThan(Long value) {
            addCriterion("GZJL_ID <", value, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdLessThanOrEqualTo(Long value) {
            addCriterion("GZJL_ID <=", value, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdIn(List<Long> values) {
            addCriterion("GZJL_ID in", values, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdNotIn(List<Long> values) {
            addCriterion("GZJL_ID not in", values, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdBetween(Long value1, Long value2) {
            addCriterion("GZJL_ID between", value1, value2, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andGzjlIdNotBetween(Long value1, Long value2) {
            addCriterion("GZJL_ID not between", value1, value2, "gzjlId");
            return (Criteria) this;
        }

        public Criteria andJhkssjIsNull() {
            addCriterion("JHKSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJhkssjIsNotNull() {
            addCriterion("JHKSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJhkssjEqualTo(String value) {
            addCriterion("JHKSSJ =", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotEqualTo(String value) {
            addCriterion("JHKSSJ <>", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjGreaterThan(String value) {
            addCriterion("JHKSSJ >", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjGreaterThanOrEqualTo(String value) {
            addCriterion("JHKSSJ >=", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjLessThan(String value) {
            addCriterion("JHKSSJ <", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjLessThanOrEqualTo(String value) {
            addCriterion("JHKSSJ <=", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjLike(String value) {
            addCriterion("JHKSSJ like", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotLike(String value) {
            addCriterion("JHKSSJ not like", value, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjIn(List<String> values) {
            addCriterion("JHKSSJ in", values, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotIn(List<String> values) {
            addCriterion("JHKSSJ not in", values, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjBetween(String value1, String value2) {
            addCriterion("JHKSSJ between", value1, value2, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhkssjNotBetween(String value1, String value2) {
            addCriterion("JHKSSJ not between", value1, value2, "jhkssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjIsNull() {
            addCriterion("JHJSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJhjssjIsNotNull() {
            addCriterion("JHJSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJhjssjEqualTo(String value) {
            addCriterion("JHJSSJ =", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotEqualTo(String value) {
            addCriterion("JHJSSJ <>", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjGreaterThan(String value) {
            addCriterion("JHJSSJ >", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjGreaterThanOrEqualTo(String value) {
            addCriterion("JHJSSJ >=", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjLessThan(String value) {
            addCriterion("JHJSSJ <", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjLessThanOrEqualTo(String value) {
            addCriterion("JHJSSJ <=", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjLike(String value) {
            addCriterion("JHJSSJ like", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotLike(String value) {
            addCriterion("JHJSSJ not like", value, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjIn(List<String> values) {
            addCriterion("JHJSSJ in", values, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotIn(List<String> values) {
            addCriterion("JHJSSJ not in", values, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjBetween(String value1, String value2) {
            addCriterion("JHJSSJ between", value1, value2, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhjssjNotBetween(String value1, String value2) {
            addCriterion("JHJSSJ not between", value1, value2, "jhjssj");
            return (Criteria) this;
        }

        public Criteria andJhlxIsNull() {
            addCriterion("JHLX is null");
            return (Criteria) this;
        }

        public Criteria andJhlxIsNotNull() {
            addCriterion("JHLX is not null");
            return (Criteria) this;
        }

        public Criteria andJhlxEqualTo(Short value) {
            addCriterion("JHLX =", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxNotEqualTo(Short value) {
            addCriterion("JHLX <>", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxGreaterThan(Short value) {
            addCriterion("JHLX >", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxGreaterThanOrEqualTo(Short value) {
            addCriterion("JHLX >=", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxLessThan(Short value) {
            addCriterion("JHLX <", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxLessThanOrEqualTo(Short value) {
            addCriterion("JHLX <=", value, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxIn(List<Short> values) {
            addCriterion("JHLX in", values, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxNotIn(List<Short> values) {
            addCriterion("JHLX not in", values, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxBetween(Short value1, Short value2) {
            addCriterion("JHLX between", value1, value2, "jhlx");
            return (Criteria) this;
        }

        public Criteria andJhlxNotBetween(Short value1, Short value2) {
            addCriterion("JHLX not between", value1, value2, "jhlx");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJLMX
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}