package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzjlscExample extends PageHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public GzjlscExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGzjlbhIsNull() {
            addCriterion("GZJLBH is null");
            return (Criteria) this;
        }

        public Criteria andGzjlbhIsNotNull() {
            addCriterion("GZJLBH is not null");
            return (Criteria) this;
        }

        public Criteria andGzjlbhEqualTo(String value) {
            addCriterion("GZJLBH =", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhNotEqualTo(String value) {
            addCriterion("GZJLBH <>", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhGreaterThan(String value) {
            addCriterion("GZJLBH >", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhGreaterThanOrEqualTo(String value) {
            addCriterion("GZJLBH >=", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhLessThan(String value) {
            addCriterion("GZJLBH <", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhLessThanOrEqualTo(String value) {
            addCriterion("GZJLBH <=", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhLike(String value) {
            addCriterion("GZJLBH like", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhNotLike(String value) {
            addCriterion("GZJLBH not like", value, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhIn(List<String> values) {
            addCriterion("GZJLBH in", values, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhNotIn(List<String> values) {
            addCriterion("GZJLBH not in", values, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhBetween(String value1, String value2) {
            addCriterion("GZJLBH between", value1, value2, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andGzjlbhNotBetween(String value1, String value2) {
            addCriterion("GZJLBH not between", value1, value2, "gzjlbh");
            return (Criteria) this;
        }

        public Criteria andJllxIsNull() {
            addCriterion("JLLX is null");
            return (Criteria) this;
        }

        public Criteria andJllxIsNotNull() {
            addCriterion("JLLX is not null");
            return (Criteria) this;
        }

        public Criteria andJllxEqualTo(Short value) {
            addCriterion("JLLX =", value, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxNotEqualTo(Short value) {
            addCriterion("JLLX <>", value, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxGreaterThan(Short value) {
            addCriterion("JLLX >", value, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxGreaterThanOrEqualTo(Short value) {
            addCriterion("JLLX >=", value, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxLessThan(Short value) {
            addCriterion("JLLX <", value, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxLessThanOrEqualTo(Short value) {
            addCriterion("JLLX <=", value, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxIn(List<Short> values) {
            addCriterion("JLLX in", values, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxNotIn(List<Short> values) {
            addCriterion("JLLX not in", values, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxBetween(Short value1, Short value2) {
            addCriterion("JLLX between", value1, value2, "jllx");
            return (Criteria) this;
        }

        public Criteria andJllxNotBetween(Short value1, Short value2) {
            addCriterion("JLLX not between", value1, value2, "jllx");
            return (Criteria) this;
        }

        public Criteria andJlsjIsNull() {
            addCriterion("JLSJ is null");
            return (Criteria) this;
        }

        public Criteria andJlsjIsNotNull() {
            addCriterion("JLSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJlsjEqualTo(Date value) {
            addCriterion("JLSJ =", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotEqualTo(Date value) {
            addCriterion("JLSJ <>", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjGreaterThan(Date value) {
            addCriterion("JLSJ >", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjGreaterThanOrEqualTo(Date value) {
            addCriterion("JLSJ >=", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLessThan(Date value) {
            addCriterion("JLSJ <", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLessThanOrEqualTo(Date value) {
            addCriterion("JLSJ <=", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjIn(List<Date> values) {
            addCriterion("JLSJ in", values, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotIn(List<Date> values) {
            addCriterion("JLSJ not in", values, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjBetween(Date value1, Date value2) {
            addCriterion("JLSJ between", value1, value2, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotBetween(Date value1, Date value2) {
            addCriterion("JLSJ not between", value1, value2, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlxzbhIsNull() {
            addCriterion("JLXZBH is null");
            return (Criteria) this;
        }

        public Criteria andJlxzbhIsNotNull() {
            addCriterion("JLXZBH is not null");
            return (Criteria) this;
        }

        public Criteria andJlxzbhEqualTo(BigDecimal value) {
            addCriterion("JLXZBH =", value, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhNotEqualTo(BigDecimal value) {
            addCriterion("JLXZBH <>", value, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhGreaterThan(BigDecimal value) {
            addCriterion("JLXZBH >", value, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("JLXZBH >=", value, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhLessThan(BigDecimal value) {
            addCriterion("JLXZBH <", value, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhLessThanOrEqualTo(BigDecimal value) {
            addCriterion("JLXZBH <=", value, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhIn(List<BigDecimal> values) {
            addCriterion("JLXZBH in", values, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhNotIn(List<BigDecimal> values) {
            addCriterion("JLXZBH not in", values, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JLXZBH between", value1, value2, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzbhNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("JLXZBH not between", value1, value2, "jlxzbh");
            return (Criteria) this;
        }

        public Criteria andJlxzmcIsNull() {
            addCriterion("JLXZMC is null");
            return (Criteria) this;
        }

        public Criteria andJlxzmcIsNotNull() {
            addCriterion("JLXZMC is not null");
            return (Criteria) this;
        }

        public Criteria andJlxzmcEqualTo(String value) {
            addCriterion("JLXZMC =", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcNotEqualTo(String value) {
            addCriterion("JLXZMC <>", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcGreaterThan(String value) {
            addCriterion("JLXZMC >", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcGreaterThanOrEqualTo(String value) {
            addCriterion("JLXZMC >=", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcLessThan(String value) {
            addCriterion("JLXZMC <", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcLessThanOrEqualTo(String value) {
            addCriterion("JLXZMC <=", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcLike(String value) {
            addCriterion("JLXZMC like", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcNotLike(String value) {
            addCriterion("JLXZMC not like", value, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcIn(List<String> values) {
            addCriterion("JLXZMC in", values, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcNotIn(List<String> values) {
            addCriterion("JLXZMC not in", values, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcBetween(String value1, String value2) {
            addCriterion("JLXZMC between", value1, value2, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andJlxzmcNotBetween(String value1, String value2) {
            addCriterion("JLXZMC not between", value1, value2, "jlxzmc");
            return (Criteria) this;
        }

        public Criteria andCfljIsNull() {
            addCriterion("CFLJ is null");
            return (Criteria) this;
        }

        public Criteria andCfljIsNotNull() {
            addCriterion("CFLJ is not null");
            return (Criteria) this;
        }

        public Criteria andCfljEqualTo(String value) {
            addCriterion("CFLJ =", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljNotEqualTo(String value) {
            addCriterion("CFLJ <>", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljGreaterThan(String value) {
            addCriterion("CFLJ >", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljGreaterThanOrEqualTo(String value) {
            addCriterion("CFLJ >=", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljLessThan(String value) {
            addCriterion("CFLJ <", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljLessThanOrEqualTo(String value) {
            addCriterion("CFLJ <=", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljLike(String value) {
            addCriterion("CFLJ like", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljNotLike(String value) {
            addCriterion("CFLJ not like", value, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljIn(List<String> values) {
            addCriterion("CFLJ in", values, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljNotIn(List<String> values) {
            addCriterion("CFLJ not in", values, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljBetween(String value1, String value2) {
            addCriterion("CFLJ between", value1, value2, "cflj");
            return (Criteria) this;
        }

        public Criteria andCfljNotBetween(String value1, String value2) {
            addCriterion("CFLJ not between", value1, value2, "cflj");
            return (Criteria) this;
        }

        public Criteria andYxbzIsNull() {
            addCriterion("YXBZ is null");
            return (Criteria) this;
        }

        public Criteria andYxbzIsNotNull() {
            addCriterion("YXBZ is not null");
            return (Criteria) this;
        }

        public Criteria andYxbzEqualTo(Short value) {
            addCriterion("YXBZ =", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotEqualTo(Short value) {
            addCriterion("YXBZ <>", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzGreaterThan(Short value) {
            addCriterion("YXBZ >", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzGreaterThanOrEqualTo(Short value) {
            addCriterion("YXBZ >=", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzLessThan(Short value) {
            addCriterion("YXBZ <", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzLessThanOrEqualTo(Short value) {
            addCriterion("YXBZ <=", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzIn(List<Short> values) {
            addCriterion("YXBZ in", values, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotIn(List<Short> values) {
            addCriterion("YXBZ not in", values, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzBetween(Short value1, Short value2) {
            addCriterion("YXBZ between", value1, value2, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotBetween(Short value1, Short value2) {
            addCriterion("YXBZ not between", value1, value2, "yxbz");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 28 22:03:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZJLSC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}