package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzxsExample  extends PageHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public GzxsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJcflIsNull() {
            addCriterion("JCFL is null");
            return (Criteria) this;
        }

        public Criteria andJcflIsNotNull() {
            addCriterion("JCFL is not null");
            return (Criteria) this;
        }

        public Criteria andJcflEqualTo(String value) {
            addCriterion("JCFL =", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflNotEqualTo(String value) {
            addCriterion("JCFL <>", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflGreaterThan(String value) {
            addCriterion("JCFL >", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflGreaterThanOrEqualTo(String value) {
            addCriterion("JCFL >=", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflLessThan(String value) {
            addCriterion("JCFL <", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflLessThanOrEqualTo(String value) {
            addCriterion("JCFL <=", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflLike(String value) {
            addCriterion("JCFL like", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflNotLike(String value) {
            addCriterion("JCFL not like", value, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflIn(List<String> values) {
            addCriterion("JCFL in", values, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflNotIn(List<String> values) {
            addCriterion("JCFL not in", values, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflBetween(String value1, String value2) {
            addCriterion("JCFL between", value1, value2, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJcflNotBetween(String value1, String value2) {
            addCriterion("JCFL not between", value1, value2, "jcfl");
            return (Criteria) this;
        }

        public Criteria andJckssjIsNull() {
            addCriterion("JCKSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJckssjIsNotNull() {
            addCriterion("JCKSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJckssjEqualTo(Date value) {
            addCriterion("JCKSSJ =", value, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjNotEqualTo(Date value) {
            addCriterion("JCKSSJ <>", value, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjGreaterThan(Date value) {
            addCriterion("JCKSSJ >", value, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JCKSSJ >=", value, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjLessThan(Date value) {
            addCriterion("JCKSSJ <", value, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjLessThanOrEqualTo(Date value) {
            addCriterion("JCKSSJ <=", value, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjIn(List<Date> values) {
            addCriterion("JCKSSJ in", values, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjNotIn(List<Date> values) {
            addCriterion("JCKSSJ not in", values, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjBetween(Date value1, Date value2) {
            addCriterion("JCKSSJ between", value1, value2, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJckssjNotBetween(Date value1, Date value2) {
            addCriterion("JCKSSJ not between", value1, value2, "jckssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjIsNull() {
            addCriterion("JCJSSJ is null");
            return (Criteria) this;
        }

        public Criteria andJcjssjIsNotNull() {
            addCriterion("JCJSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJcjssjEqualTo(Date value) {
            addCriterion("JCJSSJ =", value, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjNotEqualTo(Date value) {
            addCriterion("JCJSSJ <>", value, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjGreaterThan(Date value) {
            addCriterion("JCJSSJ >", value, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjGreaterThanOrEqualTo(Date value) {
            addCriterion("JCJSSJ >=", value, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjLessThan(Date value) {
            addCriterion("JCJSSJ <", value, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjLessThanOrEqualTo(Date value) {
            addCriterion("JCJSSJ <=", value, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjIn(List<Date> values) {
            addCriterion("JCJSSJ in", values, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjNotIn(List<Date> values) {
            addCriterion("JCJSSJ not in", values, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjBetween(Date value1, Date value2) {
            addCriterion("JCJSSJ between", value1, value2, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcjssjNotBetween(Date value1, Date value2) {
            addCriterion("JCJSSJ not between", value1, value2, "jcjssj");
            return (Criteria) this;
        }

        public Criteria andJcryIsNull() {
            addCriterion("JCRY is null");
            return (Criteria) this;
        }

        public Criteria andJcryIsNotNull() {
            addCriterion("JCRY is not null");
            return (Criteria) this;
        }

        public Criteria andJcryEqualTo(String value) {
            addCriterion("JCRY =", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryNotEqualTo(String value) {
            addCriterion("JCRY <>", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryGreaterThan(String value) {
            addCriterion("JCRY >", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryGreaterThanOrEqualTo(String value) {
            addCriterion("JCRY >=", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryLessThan(String value) {
            addCriterion("JCRY <", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryLessThanOrEqualTo(String value) {
            addCriterion("JCRY <=", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryLike(String value) {
            addCriterion("JCRY like", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryNotLike(String value) {
            addCriterion("JCRY not like", value, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryIn(List<String> values) {
            addCriterion("JCRY in", values, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryNotIn(List<String> values) {
            addCriterion("JCRY not in", values, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryBetween(String value1, String value2) {
            addCriterion("JCRY between", value1, value2, "jcry");
            return (Criteria) this;
        }

        public Criteria andJcryNotBetween(String value1, String value2) {
            addCriterion("JCRY not between", value1, value2, "jcry");
            return (Criteria) this;
        }

        public Criteria andPtryIsNull() {
            addCriterion("PTRY is null");
            return (Criteria) this;
        }

        public Criteria andPtryIsNotNull() {
            addCriterion("PTRY is not null");
            return (Criteria) this;
        }

        public Criteria andPtryEqualTo(String value) {
            addCriterion("PTRY =", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryNotEqualTo(String value) {
            addCriterion("PTRY <>", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryGreaterThan(String value) {
            addCriterion("PTRY >", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryGreaterThanOrEqualTo(String value) {
            addCriterion("PTRY >=", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryLessThan(String value) {
            addCriterion("PTRY <", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryLessThanOrEqualTo(String value) {
            addCriterion("PTRY <=", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryLike(String value) {
            addCriterion("PTRY like", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryNotLike(String value) {
            addCriterion("PTRY not like", value, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryIn(List<String> values) {
            addCriterion("PTRY in", values, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryNotIn(List<String> values) {
            addCriterion("PTRY not in", values, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryBetween(String value1, String value2) {
            addCriterion("PTRY between", value1, value2, "ptry");
            return (Criteria) this;
        }

        public Criteria andPtryNotBetween(String value1, String value2) {
            addCriterion("PTRY not between", value1, value2, "ptry");
            return (Criteria) this;
        }

        public Criteria andQtryIsNull() {
            addCriterion("QTRY is null");
            return (Criteria) this;
        }

        public Criteria andQtryIsNotNull() {
            addCriterion("QTRY is not null");
            return (Criteria) this;
        }

        public Criteria andQtryEqualTo(String value) {
            addCriterion("QTRY =", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryNotEqualTo(String value) {
            addCriterion("QTRY <>", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryGreaterThan(String value) {
            addCriterion("QTRY >", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryGreaterThanOrEqualTo(String value) {
            addCriterion("QTRY >=", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryLessThan(String value) {
            addCriterion("QTRY <", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryLessThanOrEqualTo(String value) {
            addCriterion("QTRY <=", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryLike(String value) {
            addCriterion("QTRY like", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryNotLike(String value) {
            addCriterion("QTRY not like", value, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryIn(List<String> values) {
            addCriterion("QTRY in", values, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryNotIn(List<String> values) {
            addCriterion("QTRY not in", values, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryBetween(String value1, String value2) {
            addCriterion("QTRY between", value1, value2, "qtry");
            return (Criteria) this;
        }

        public Criteria andQtryNotBetween(String value1, String value2) {
            addCriterion("QTRY not between", value1, value2, "qtry");
            return (Criteria) this;
        }

        public Criteria andJczlsjdIsNull() {
            addCriterion("JCZLSJD is null");
            return (Criteria) this;
        }

        public Criteria andJczlsjdIsNotNull() {
            addCriterion("JCZLSJD is not null");
            return (Criteria) this;
        }

        public Criteria andJczlsjdEqualTo(String value) {
            addCriterion("JCZLSJD =", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdNotEqualTo(String value) {
            addCriterion("JCZLSJD <>", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdGreaterThan(String value) {
            addCriterion("JCZLSJD >", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdGreaterThanOrEqualTo(String value) {
            addCriterion("JCZLSJD >=", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdLessThan(String value) {
            addCriterion("JCZLSJD <", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdLessThanOrEqualTo(String value) {
            addCriterion("JCZLSJD <=", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdLike(String value) {
            addCriterion("JCZLSJD like", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdNotLike(String value) {
            addCriterion("JCZLSJD not like", value, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdIn(List<String> values) {
            addCriterion("JCZLSJD in", values, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdNotIn(List<String> values) {
            addCriterion("JCZLSJD not in", values, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdBetween(String value1, String value2) {
            addCriterion("JCZLSJD between", value1, value2, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andJczlsjdNotBetween(String value1, String value2) {
            addCriterion("JCZLSJD not between", value1, value2, "jczlsjd");
            return (Criteria) this;
        }

        public Criteria andTy1IsNull() {
            addCriterion("TY1 is null");
            return (Criteria) this;
        }

        public Criteria andTy1IsNotNull() {
            addCriterion("TY1 is not null");
            return (Criteria) this;
        }

        public Criteria andTy1EqualTo(String value) {
            addCriterion("TY1 =", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1NotEqualTo(String value) {
            addCriterion("TY1 <>", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1GreaterThan(String value) {
            addCriterion("TY1 >", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1GreaterThanOrEqualTo(String value) {
            addCriterion("TY1 >=", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1LessThan(String value) {
            addCriterion("TY1 <", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1LessThanOrEqualTo(String value) {
            addCriterion("TY1 <=", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1Like(String value) {
            addCriterion("TY1 like", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1NotLike(String value) {
            addCriterion("TY1 not like", value, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1In(List<String> values) {
            addCriterion("TY1 in", values, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1NotIn(List<String> values) {
            addCriterion("TY1 not in", values, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1Between(String value1, String value2) {
            addCriterion("TY1 between", value1, value2, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy1NotBetween(String value1, String value2) {
            addCriterion("TY1 not between", value1, value2, "ty1");
            return (Criteria) this;
        }

        public Criteria andTy2IsNull() {
            addCriterion("TY2 is null");
            return (Criteria) this;
        }

        public Criteria andTy2IsNotNull() {
            addCriterion("TY2 is not null");
            return (Criteria) this;
        }

        public Criteria andTy2EqualTo(String value) {
            addCriterion("TY2 =", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2NotEqualTo(String value) {
            addCriterion("TY2 <>", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2GreaterThan(String value) {
            addCriterion("TY2 >", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2GreaterThanOrEqualTo(String value) {
            addCriterion("TY2 >=", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2LessThan(String value) {
            addCriterion("TY2 <", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2LessThanOrEqualTo(String value) {
            addCriterion("TY2 <=", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2Like(String value) {
            addCriterion("TY2 like", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2NotLike(String value) {
            addCriterion("TY2 not like", value, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2In(List<String> values) {
            addCriterion("TY2 in", values, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2NotIn(List<String> values) {
            addCriterion("TY2 not in", values, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2Between(String value1, String value2) {
            addCriterion("TY2 between", value1, value2, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy2NotBetween(String value1, String value2) {
            addCriterion("TY2 not between", value1, value2, "ty2");
            return (Criteria) this;
        }

        public Criteria andTy3IsNull() {
            addCriterion("TY3 is null");
            return (Criteria) this;
        }

        public Criteria andTy3IsNotNull() {
            addCriterion("TY3 is not null");
            return (Criteria) this;
        }

        public Criteria andTy3EqualTo(String value) {
            addCriterion("TY3 =", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3NotEqualTo(String value) {
            addCriterion("TY3 <>", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3GreaterThan(String value) {
            addCriterion("TY3 >", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3GreaterThanOrEqualTo(String value) {
            addCriterion("TY3 >=", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3LessThan(String value) {
            addCriterion("TY3 <", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3LessThanOrEqualTo(String value) {
            addCriterion("TY3 <=", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3Like(String value) {
            addCriterion("TY3 like", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3NotLike(String value) {
            addCriterion("TY3 not like", value, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3In(List<String> values) {
            addCriterion("TY3 in", values, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3NotIn(List<String> values) {
            addCriterion("TY3 not in", values, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3Between(String value1, String value2) {
            addCriterion("TY3 between", value1, value2, "ty3");
            return (Criteria) this;
        }

        public Criteria andTy3NotBetween(String value1, String value2) {
            addCriterion("TY3 not between", value1, value2, "ty3");
            return (Criteria) this;
        }

        public Criteria andLclxIsNull() {
            addCriterion("LCLX is null");
            return (Criteria) this;
        }

        public Criteria andLclxIsNotNull() {
            addCriterion("LCLX is not null");
            return (Criteria) this;
        }

        public Criteria andLclxEqualTo(String value) {
            addCriterion("LCLX =", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxNotEqualTo(String value) {
            addCriterion("LCLX <>", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxGreaterThan(String value) {
            addCriterion("LCLX >", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxGreaterThanOrEqualTo(String value) {
            addCriterion("LCLX >=", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxLessThan(String value) {
            addCriterion("LCLX <", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxLessThanOrEqualTo(String value) {
            addCriterion("LCLX <=", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxLike(String value) {
            addCriterion("LCLX like", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxNotLike(String value) {
            addCriterion("LCLX not like", value, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxIn(List<String> values) {
            addCriterion("LCLX in", values, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxNotIn(List<String> values) {
            addCriterion("LCLX not in", values, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxBetween(String value1, String value2) {
            addCriterion("LCLX between", value1, value2, "lclx");
            return (Criteria) this;
        }

        public Criteria andLclxNotBetween(String value1, String value2) {
            addCriterion("LCLX not between", value1, value2, "lclx");
            return (Criteria) this;
        }

        public Criteria andBcccIsNull() {
            addCriterion("BCCC is null");
            return (Criteria) this;
        }

        public Criteria andBcccIsNotNull() {
            addCriterion("BCCC is not null");
            return (Criteria) this;
        }

        public Criteria andBcccEqualTo(String value) {
            addCriterion("BCCC =", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccNotEqualTo(String value) {
            addCriterion("BCCC <>", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccGreaterThan(String value) {
            addCriterion("BCCC >", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccGreaterThanOrEqualTo(String value) {
            addCriterion("BCCC >=", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccLessThan(String value) {
            addCriterion("BCCC <", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccLessThanOrEqualTo(String value) {
            addCriterion("BCCC <=", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccLike(String value) {
            addCriterion("BCCC like", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccNotLike(String value) {
            addCriterion("BCCC not like", value, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccIn(List<String> values) {
            addCriterion("BCCC in", values, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccNotIn(List<String> values) {
            addCriterion("BCCC not in", values, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccBetween(String value1, String value2) {
            addCriterion("BCCC between", value1, value2, "bccc");
            return (Criteria) this;
        }

        public Criteria andBcccNotBetween(String value1, String value2) {
            addCriterion("BCCC not between", value1, value2, "bccc");
            return (Criteria) this;
        }

        public Criteria andJcksqjIsNull() {
            addCriterion("JCKSQJ is null");
            return (Criteria) this;
        }

        public Criteria andJcksqjIsNotNull() {
            addCriterion("JCKSQJ is not null");
            return (Criteria) this;
        }

        public Criteria andJcksqjEqualTo(String value) {
            addCriterion("JCKSQJ =", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjNotEqualTo(String value) {
            addCriterion("JCKSQJ <>", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjGreaterThan(String value) {
            addCriterion("JCKSQJ >", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjGreaterThanOrEqualTo(String value) {
            addCriterion("JCKSQJ >=", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjLessThan(String value) {
            addCriterion("JCKSQJ <", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjLessThanOrEqualTo(String value) {
            addCriterion("JCKSQJ <=", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjLike(String value) {
            addCriterion("JCKSQJ like", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjNotLike(String value) {
            addCriterion("JCKSQJ not like", value, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjIn(List<String> values) {
            addCriterion("JCKSQJ in", values, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjNotIn(List<String> values) {
            addCriterion("JCKSQJ not in", values, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjBetween(String value1, String value2) {
            addCriterion("JCKSQJ between", value1, value2, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcksqjNotBetween(String value1, String value2) {
            addCriterion("JCKSQJ not between", value1, value2, "jcksqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjIsNull() {
            addCriterion("JCJSQJ is null");
            return (Criteria) this;
        }

        public Criteria andJcjsqjIsNotNull() {
            addCriterion("JCJSQJ is not null");
            return (Criteria) this;
        }

        public Criteria andJcjsqjEqualTo(String value) {
            addCriterion("JCJSQJ =", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjNotEqualTo(String value) {
            addCriterion("JCJSQJ <>", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjGreaterThan(String value) {
            addCriterion("JCJSQJ >", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjGreaterThanOrEqualTo(String value) {
            addCriterion("JCJSQJ >=", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjLessThan(String value) {
            addCriterion("JCJSQJ <", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjLessThanOrEqualTo(String value) {
            addCriterion("JCJSQJ <=", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjLike(String value) {
            addCriterion("JCJSQJ like", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjNotLike(String value) {
            addCriterion("JCJSQJ not like", value, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjIn(List<String> values) {
            addCriterion("JCJSQJ in", values, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjNotIn(List<String> values) {
            addCriterion("JCJSQJ not in", values, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjBetween(String value1, String value2) {
            addCriterion("JCJSQJ between", value1, value2, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andJcjsqjNotBetween(String value1, String value2) {
            addCriterion("JCJSQJ not between", value1, value2, "jcjsqj");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andLxIsNull() {
            addCriterion("LX is null");
            return (Criteria) this;
        }

        public Criteria andLxIsNotNull() {
            addCriterion("LX is not null");
            return (Criteria) this;
        }

        public Criteria andLxEqualTo(Short value) {
            addCriterion("LX =", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotEqualTo(Short value) {
            addCriterion("LX <>", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxGreaterThan(Short value) {
            addCriterion("LX >", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxGreaterThanOrEqualTo(Short value) {
            addCriterion("LX >=", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLessThan(Short value) {
            addCriterion("LX <", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLessThanOrEqualTo(Short value) {
            addCriterion("LX <=", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxIn(List<Short> values) {
            addCriterion("LX in", values, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotIn(List<Short> values) {
            addCriterion("LX not in", values, "lx");
            return (Criteria) this;
        }

        public Criteria andLxBetween(Short value1, Short value2) {
            addCriterion("LX between", value1, value2, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotBetween(Short value1, Short value2) {
            addCriterion("LX not between", value1, value2, "lx");
            return (Criteria) this;
        }

        public Criteria andWorkNumberIsNull() {
            addCriterion("WORK_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andWorkNumberIsNotNull() {
            addCriterion("WORK_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andWorkNumberEqualTo(Short value) {
            addCriterion("WORK_NUMBER =", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberNotEqualTo(Short value) {
            addCriterion("WORK_NUMBER <>", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberGreaterThan(Short value) {
            addCriterion("WORK_NUMBER >", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberGreaterThanOrEqualTo(Short value) {
            addCriterion("WORK_NUMBER >=", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberLessThan(Short value) {
            addCriterion("WORK_NUMBER <", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberLessThanOrEqualTo(Short value) {
            addCriterion("WORK_NUMBER <=", value, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberIn(List<Short> values) {
            addCriterion("WORK_NUMBER in", values, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberNotIn(List<Short> values) {
            addCriterion("WORK_NUMBER not in", values, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberBetween(Short value1, Short value2) {
            addCriterion("WORK_NUMBER between", value1, value2, "workNumber");
            return (Criteria) this;
        }

        public Criteria andWorkNumberNotBetween(Short value1, Short value2) {
            addCriterion("WORK_NUMBER not between", value1, value2, "workNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 07 17:16:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZXS
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}