package com.core.model.checkmis;

import java.util.Date;

public class GzxsJcqkbMx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCQKB_ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private Long jcqkbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSX_ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private Long jcxdsxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSJ
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private String jcxdsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.CREATEDATE
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYDATE
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.CREATEUSER
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYUSER
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    private String modifyuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.ID
     *
     * @param id the value for CHECKMIS.ST_GZXS_JCQKB_MX.ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCQKB_ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.JCQKB_ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public Long getJcqkbId() {
        return jcqkbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCQKB_ID
     *
     * @param jcqkbId the value for CHECKMIS.ST_GZXS_JCQKB_MX.JCQKB_ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setJcqkbId(Long jcqkbId) {
        this.jcqkbId = jcqkbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSX_ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSX_ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public Long getJcxdsxId() {
        return jcxdsxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSX_ID
     *
     * @param jcxdsxId the value for CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSX_ID
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setJcxdsxId(Long jcxdsxId) {
        this.jcxdsxId = jcxdsxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSJ
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSJ
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public String getJcxdsj() {
        return jcxdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSJ
     *
     * @param jcxdsj the value for CHECKMIS.ST_GZXS_JCQKB_MX.JCXDSJ
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setJcxdsj(String jcxdsj) {
        this.jcxdsj = jcxdsj == null ? null : jcxdsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.CREATEDATE
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.CREATEDATE
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.CREATEDATE
     *
     * @param createdate the value for CHECKMIS.ST_GZXS_JCQKB_MX.CREATEDATE
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYDATE
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYDATE
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYDATE
     *
     * @param modifydate the value for CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYDATE
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.CREATEUSER
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.CREATEUSER
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.CREATEUSER
     *
     * @param createuser the value for CHECKMIS.ST_GZXS_JCQKB_MX.CREATEUSER
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYUSER
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYUSER
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYUSER
     *
     * @param modifyuser the value for CHECKMIS.ST_GZXS_JCQKB_MX.MODIFYUSER
     *
     * @mbg.generated Sun Nov 25 13:54:42 CST 2018
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser == null ? null : modifyuser.trim();
    }
}