package com.core.model.checkmis;

import java.util.Date;

public class GzxsJtwt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.ID
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.GZXS_ID
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private Long gzxsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.WTFL
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String wtfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.WTXD
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String wtxd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.JTNR
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String jtnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.ZYZRDW
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String zyzrdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.XGZRDW
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String xgzrdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.WTZT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private Short wtzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.CREATEDATE
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.MODIFYDATE
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.CREATEUSER
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JTWT.MODIFYUSER
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    private String modifyuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.ID
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.ID
     *
     * @param id the value for CHECKMIS.ST_GZXS_JTWT.ID
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.GZXS_ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.GZXS_ID
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Long getGzxsId() {
        return gzxsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.GZXS_ID
     *
     * @param gzxsId the value for CHECKMIS.ST_GZXS_JTWT.GZXS_ID
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setGzxsId(Long gzxsId) {
        this.gzxsId = gzxsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.WTFL
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.WTFL
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getWtfl() {
        return wtfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.WTFL
     *
     * @param wtfl the value for CHECKMIS.ST_GZXS_JTWT.WTFL
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setWtfl(String wtfl) {
        this.wtfl = wtfl == null ? null : wtfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.WTXD
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.WTXD
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getWtxd() {
        return wtxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.WTXD
     *
     * @param wtxd the value for CHECKMIS.ST_GZXS_JTWT.WTXD
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setWtxd(String wtxd) {
        this.wtxd = wtxd == null ? null : wtxd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.JTNR
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.JTNR
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getJtnr() {
        return jtnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.JTNR
     *
     * @param jtnr the value for CHECKMIS.ST_GZXS_JTWT.JTNR
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setJtnr(String jtnr) {
        this.jtnr = jtnr == null ? null : jtnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.ZYZRDW
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.ZYZRDW
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getZyzrdw() {
        return zyzrdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.ZYZRDW
     *
     * @param zyzrdw the value for CHECKMIS.ST_GZXS_JTWT.ZYZRDW
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setZyzrdw(String zyzrdw) {
        this.zyzrdw = zyzrdw == null ? null : zyzrdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.XGZRDW
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.XGZRDW
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getXgzrdw() {
        return xgzrdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.XGZRDW
     *
     * @param xgzrdw the value for CHECKMIS.ST_GZXS_JTWT.XGZRDW
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setXgzrdw(String xgzrdw) {
        this.xgzrdw = xgzrdw == null ? null : xgzrdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.WTZT
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.WTZT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Short getWtzt() {
        return wtzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.WTZT
     *
     * @param wtzt the value for CHECKMIS.ST_GZXS_JTWT.WTZT
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setWtzt(Short wtzt) {
        this.wtzt = wtzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.CREATEDATE
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.CREATEDATE
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.CREATEDATE
     *
     * @param createdate the value for CHECKMIS.ST_GZXS_JTWT.CREATEDATE
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.MODIFYDATE
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.MODIFYDATE
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.MODIFYDATE
     *
     * @param modifydate the value for CHECKMIS.ST_GZXS_JTWT.MODIFYDATE
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.CREATEUSER
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.CREATEUSER
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.CREATEUSER
     *
     * @param createuser the value for CHECKMIS.ST_GZXS_JTWT.CREATEUSER
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JTWT.MODIFYUSER
     *
     * @return the value of CHECKMIS.ST_GZXS_JTWT.MODIFYUSER
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JTWT.MODIFYUSER
     *
     * @param modifyuser the value for CHECKMIS.ST_GZXS_JTWT.MODIFYUSER
     *
     * @mbggenerated Sun Oct 07 17:16:39 CST 2018
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser == null ? null : modifyuser.trim();
    }
}