package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JcxdsxExample extends PageHelper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public JcxdsxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJcflIdIsNull() {
            addCriterion("JCFL_ID is null");
            return (Criteria) this;
        }

        public Criteria andJcflIdIsNotNull() {
            addCriterion("JCFL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJcflIdEqualTo(Long value) {
            addCriterion("JCFL_ID =", value, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdNotEqualTo(Long value) {
            addCriterion("JCFL_ID <>", value, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdGreaterThan(Long value) {
            addCriterion("JCFL_ID >", value, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdGreaterThanOrEqualTo(Long value) {
            addCriterion("JCFL_ID >=", value, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdLessThan(Long value) {
            addCriterion("JCFL_ID <", value, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdLessThanOrEqualTo(Long value) {
            addCriterion("JCFL_ID <=", value, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdIn(List<Long> values) {
            addCriterion("JCFL_ID in", values, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdNotIn(List<Long> values) {
            addCriterion("JCFL_ID not in", values, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdBetween(Long value1, Long value2) {
            addCriterion("JCFL_ID between", value1, value2, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcflIdNotBetween(Long value1, Long value2) {
            addCriterion("JCFL_ID not between", value1, value2, "jcflId");
            return (Criteria) this;
        }

        public Criteria andJcxdsxIsNull() {
            addCriterion("JCXDSX is null");
            return (Criteria) this;
        }

        public Criteria andJcxdsxIsNotNull() {
            addCriterion("JCXDSX is not null");
            return (Criteria) this;
        }

        public Criteria andJcxdsxEqualTo(String value) {
            addCriterion("JCXDSX =", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxNotEqualTo(String value) {
            addCriterion("JCXDSX <>", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxGreaterThan(String value) {
            addCriterion("JCXDSX >", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxGreaterThanOrEqualTo(String value) {
            addCriterion("JCXDSX >=", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxLessThan(String value) {
            addCriterion("JCXDSX <", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxLessThanOrEqualTo(String value) {
            addCriterion("JCXDSX <=", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxLike(String value) {
            addCriterion("JCXDSX like", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxNotLike(String value) {
            addCriterion("JCXDSX not like", value, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxIn(List<String> values) {
            addCriterion("JCXDSX in", values, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxNotIn(List<String> values) {
            addCriterion("JCXDSX not in", values, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxBetween(String value1, String value2) {
            addCriterion("JCXDSX between", value1, value2, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxNotBetween(String value1, String value2) {
            addCriterion("JCXDSX not between", value1, value2, "jcxdsx");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwIsNull() {
            addCriterion("JCXDSXDW is null");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwIsNotNull() {
            addCriterion("JCXDSXDW is not null");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwEqualTo(String value) {
            addCriterion("JCXDSXDW =", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwNotEqualTo(String value) {
            addCriterion("JCXDSXDW <>", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwGreaterThan(String value) {
            addCriterion("JCXDSXDW >", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwGreaterThanOrEqualTo(String value) {
            addCriterion("JCXDSXDW >=", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwLessThan(String value) {
            addCriterion("JCXDSXDW <", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwLessThanOrEqualTo(String value) {
            addCriterion("JCXDSXDW <=", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwLike(String value) {
            addCriterion("JCXDSXDW like", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwNotLike(String value) {
            addCriterion("JCXDSXDW not like", value, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwIn(List<String> values) {
            addCriterion("JCXDSXDW in", values, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwNotIn(List<String> values) {
            addCriterion("JCXDSXDW not in", values, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwBetween(String value1, String value2) {
            addCriterion("JCXDSXDW between", value1, value2, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andJcxdsxdwNotBetween(String value1, String value2) {
            addCriterion("JCXDSXDW not between", value1, value2, "jcxdsxdw");
            return (Criteria) this;
        }

        public Criteria andOrdersIsNull() {
            addCriterion("ORDERS is null");
            return (Criteria) this;
        }

        public Criteria andOrdersIsNotNull() {
            addCriterion("ORDERS is not null");
            return (Criteria) this;
        }

        public Criteria andOrdersEqualTo(Integer value) {
            addCriterion("ORDERS =", value, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersNotEqualTo(Integer value) {
            addCriterion("ORDERS <>", value, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersGreaterThan(Integer value) {
            addCriterion("ORDERS >", value, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDERS >=", value, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersLessThan(Integer value) {
            addCriterion("ORDERS <", value, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersLessThanOrEqualTo(Integer value) {
            addCriterion("ORDERS <=", value, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersIn(List<Integer> values) {
            addCriterion("ORDERS in", values, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersNotIn(List<Integer> values) {
            addCriterion("ORDERS not in", values, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersBetween(Integer value1, Integer value2) {
            addCriterion("ORDERS between", value1, value2, "orders");
            return (Criteria) this;
        }

        public Criteria andOrdersNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDERS not between", value1, value2, "orders");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 14 08:13:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_JCXDSX
     *
     * @mbg.generated Wed Nov 14 08:13:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}