package com.core.model.checkmis;

import java.math.BigDecimal;
import java.util.Date;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.PARENT_ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private BigDecimal parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.CODE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.NAME
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.PHONE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.FAX
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.OWNER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.OWNER_PHONE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String ownerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.TYPE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private BigDecimal type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.CREATEDATE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.MODIFYDATE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.CREATEUSER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.MODIFYUSER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private String modifyuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.UNIT_ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private BigDecimal unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.SYS_DEPT.SERIAL
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    private Short serial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.ID
     *
     * @return the value of CHECKMIS.SYS_DEPT.ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.ID
     *
     * @param id the value for CHECKMIS.SYS_DEPT.ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.PARENT_ID
     *
     * @return the value of CHECKMIS.SYS_DEPT.PARENT_ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public BigDecimal getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.PARENT_ID
     *
     * @param parentId the value for CHECKMIS.SYS_DEPT.PARENT_ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setParentId(BigDecimal parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.CODE
     *
     * @return the value of CHECKMIS.SYS_DEPT.CODE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.CODE
     *
     * @param code the value for CHECKMIS.SYS_DEPT.CODE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.NAME
     *
     * @return the value of CHECKMIS.SYS_DEPT.NAME
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.NAME
     *
     * @param name the value for CHECKMIS.SYS_DEPT.NAME
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.PHONE
     *
     * @return the value of CHECKMIS.SYS_DEPT.PHONE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.PHONE
     *
     * @param phone the value for CHECKMIS.SYS_DEPT.PHONE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.FAX
     *
     * @return the value of CHECKMIS.SYS_DEPT.FAX
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.FAX
     *
     * @param fax the value for CHECKMIS.SYS_DEPT.FAX
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.OWNER
     *
     * @return the value of CHECKMIS.SYS_DEPT.OWNER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.OWNER
     *
     * @param owner the value for CHECKMIS.SYS_DEPT.OWNER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.OWNER_PHONE
     *
     * @return the value of CHECKMIS.SYS_DEPT.OWNER_PHONE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getOwnerPhone() {
        return ownerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.OWNER_PHONE
     *
     * @param ownerPhone the value for CHECKMIS.SYS_DEPT.OWNER_PHONE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setOwnerPhone(String ownerPhone) {
        this.ownerPhone = ownerPhone == null ? null : ownerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.TYPE
     *
     * @return the value of CHECKMIS.SYS_DEPT.TYPE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.TYPE
     *
     * @param type the value for CHECKMIS.SYS_DEPT.TYPE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.CREATEDATE
     *
     * @return the value of CHECKMIS.SYS_DEPT.CREATEDATE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.CREATEDATE
     *
     * @param createdate the value for CHECKMIS.SYS_DEPT.CREATEDATE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.MODIFYDATE
     *
     * @return the value of CHECKMIS.SYS_DEPT.MODIFYDATE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.MODIFYDATE
     *
     * @param modifydate the value for CHECKMIS.SYS_DEPT.MODIFYDATE
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.CREATEUSER
     *
     * @return the value of CHECKMIS.SYS_DEPT.CREATEUSER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.CREATEUSER
     *
     * @param createuser the value for CHECKMIS.SYS_DEPT.CREATEUSER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.MODIFYUSER
     *
     * @return the value of CHECKMIS.SYS_DEPT.MODIFYUSER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.MODIFYUSER
     *
     * @param modifyuser the value for CHECKMIS.SYS_DEPT.MODIFYUSER
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser == null ? null : modifyuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.UNIT_ID
     *
     * @return the value of CHECKMIS.SYS_DEPT.UNIT_ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public BigDecimal getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.UNIT_ID
     *
     * @param unitId the value for CHECKMIS.SYS_DEPT.UNIT_ID
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setUnitId(BigDecimal unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.SYS_DEPT.SERIAL
     *
     * @return the value of CHECKMIS.SYS_DEPT.SERIAL
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public Short getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.SYS_DEPT.SERIAL
     *
     * @param serial the value for CHECKMIS.SYS_DEPT.SERIAL
     *
     * @mbg.generated Wed Oct 17 22:51:44 CST 2018
     */
    public void setSerial(Short serial) {
        this.serial = serial;
    }
}