package com.core.model.checkmis;

import java.math.BigDecimal;
import java.util.Date;

public class Gzjlsc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.ID
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.GZJLBH
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private String gzjlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.JLLX
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private Short jllx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.JLSJ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private Date jlsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.JLXZBH
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private BigDecimal jlxzbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.JLXZMC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private String jlxzmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.CFLJ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private String cflj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.YXBZ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private Short yxbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.CREATEDATE
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.MODIFYDATE
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.CREATEUSER
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZJLSC.MODIFYUSER
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    private String modifyuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.ID
     *
     * @return the value of CHECKMIS.ST_GZJLSC.ID
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.ID
     *
     * @param id the value for CHECKMIS.ST_GZJLSC.ID
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.GZJLBH
     *
     * @return the value of CHECKMIS.ST_GZJLSC.GZJLBH
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public String getGzjlbh() {
        return gzjlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.GZJLBH
     *
     * @param gzjlbh the value for CHECKMIS.ST_GZJLSC.GZJLBH
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setGzjlbh(String gzjlbh) {
        this.gzjlbh = gzjlbh == null ? null : gzjlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.JLLX
     *
     * @return the value of CHECKMIS.ST_GZJLSC.JLLX
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Short getJllx() {
        return jllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.JLLX
     *
     * @param jllx the value for CHECKMIS.ST_GZJLSC.JLLX
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setJllx(Short jllx) {
        this.jllx = jllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.JLSJ
     *
     * @return the value of CHECKMIS.ST_GZJLSC.JLSJ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Date getJlsj() {
        return jlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.JLSJ
     *
     * @param jlsj the value for CHECKMIS.ST_GZJLSC.JLSJ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setJlsj(Date jlsj) {
        this.jlsj = jlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.JLXZBH
     *
     * @return the value of CHECKMIS.ST_GZJLSC.JLXZBH
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public BigDecimal getJlxzbh() {
        return jlxzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.JLXZBH
     *
     * @param jlxzbh the value for CHECKMIS.ST_GZJLSC.JLXZBH
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setJlxzbh(BigDecimal jlxzbh) {
        this.jlxzbh = jlxzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.JLXZMC
     *
     * @return the value of CHECKMIS.ST_GZJLSC.JLXZMC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public String getJlxzmc() {
        return jlxzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.JLXZMC
     *
     * @param jlxzmc the value for CHECKMIS.ST_GZJLSC.JLXZMC
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setJlxzmc(String jlxzmc) {
        this.jlxzmc = jlxzmc == null ? null : jlxzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.CFLJ
     *
     * @return the value of CHECKMIS.ST_GZJLSC.CFLJ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public String getCflj() {
        return cflj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.CFLJ
     *
     * @param cflj the value for CHECKMIS.ST_GZJLSC.CFLJ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setCflj(String cflj) {
        this.cflj = cflj == null ? null : cflj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.YXBZ
     *
     * @return the value of CHECKMIS.ST_GZJLSC.YXBZ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Short getYxbz() {
        return yxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.YXBZ
     *
     * @param yxbz the value for CHECKMIS.ST_GZJLSC.YXBZ
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setYxbz(Short yxbz) {
        this.yxbz = yxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.CREATEDATE
     *
     * @return the value of CHECKMIS.ST_GZJLSC.CREATEDATE
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.CREATEDATE
     *
     * @param createdate the value for CHECKMIS.ST_GZJLSC.CREATEDATE
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.MODIFYDATE
     *
     * @return the value of CHECKMIS.ST_GZJLSC.MODIFYDATE
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.MODIFYDATE
     *
     * @param modifydate the value for CHECKMIS.ST_GZJLSC.MODIFYDATE
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.CREATEUSER
     *
     * @return the value of CHECKMIS.ST_GZJLSC.CREATEUSER
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.CREATEUSER
     *
     * @param createuser the value for CHECKMIS.ST_GZJLSC.CREATEUSER
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZJLSC.MODIFYUSER
     *
     * @return the value of CHECKMIS.ST_GZJLSC.MODIFYUSER
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZJLSC.MODIFYUSER
     *
     * @param modifyuser the value for CHECKMIS.ST_GZJLSC.MODIFYUSER
     *
     * @mbg.generated Sun Oct 28 22:03:38 CST 2018
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser == null ? null : modifyuser.trim();
    }
}