package com.dao.core.checkmis;

import com.core.model.checkmis.JcflDmb;
import com.core.model.checkmis.JcflDmbExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JcflDmbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    long countByExample(JcflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int deleteByExample(JcflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int insert(JcflDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int insertSelective(JcflDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    List<JcflDmb> selectByExample(JcflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    JcflDmb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") JcflDmb record, @Param("example") JcflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int updateByExample(@Param("record") JcflDmb record, @Param("example") JcflDmbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int updateByPrimaryKeySelective(JcflDmb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_JCFL_DMB
     *
     * @mbg.generated Tue Nov 13 01:41:35 CST 2018
     */
    int updateByPrimaryKey(JcflDmb record);
}