package com.dao.core.checkmis;

import com.core.model.checkmis.AppMessage;
import com.core.model.checkmis.AppMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    long countByExample(AppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int deleteByExample(AppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int insert(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int insertSelective(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    List<AppMessage> selectByExample(AppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    AppMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppMessage record, @Param("example") AppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppMessage record, @Param("example") AppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_APP_MESSAGE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppMessage record);
}