package com.dao.core.checkmis;

import com.api.dto.ApiGzjlDto;
import com.biz.dto.gzjl.GzjlDto;
import com.core.model.checkmis.Gzjl;
import com.core.model.checkmis.GzjlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GzjlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    long countByExample(GzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int deleteByExample(GzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int insert(Gzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int insertSelective(Gzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    List<Gzjl> selectByExample(GzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    Gzjl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gzjl record, @Param("example") GzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gzjl record, @Param("example") GzjlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gzjl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZJL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gzjl record);

    List<GzjlDto> selectGzJlListByGzrw(Long gzrwId);

    List<GzjlDto> selectGzJlZZListByGzrw(Long gzrwId);


}