package com.dao.core.checkmis;

import com.core.dto.DropDownDto;
import com.core.model.checkmis.CodeListDetail;
import com.core.model.checkmis.CodeListDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeListDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    long countByExample(CodeListDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int deleteByExample(CodeListDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int insert(CodeListDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int insertSelective(CodeListDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    List<CodeListDetail> selectByExample(CodeListDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    CodeListDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CodeListDetail record, @Param("example") CodeListDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CodeListDetail record, @Param("example") CodeListDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CodeListDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.SYS_CODELIST_DETAIL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CodeListDetail record);

    List<DropDownDto> queryAllData();
}