package com.core.model.checkmis;

import java.util.Date;

public class GzxsJcqkb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.GZXS_ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private Long gzxsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.JCFL_ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private Long jcflId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.ZT
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private Integer zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.CREATEDATE
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.MODIFYDATE
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.CREATEUSER
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.MODIFYUSER
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private String modifyuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECKMIS.ST_GZXS_JCQKB.JCFLMC
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    private String jcflmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.ID
     *
     * @param id the value for CHECKMIS.ST_GZXS_JCQKB.ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.GZXS_ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.GZXS_ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public Long getGzxsId() {
        return gzxsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.GZXS_ID
     *
     * @param gzxsId the value for CHECKMIS.ST_GZXS_JCQKB.GZXS_ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setGzxsId(Long gzxsId) {
        this.gzxsId = gzxsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.JCFL_ID
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.JCFL_ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public Long getJcflId() {
        return jcflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.JCFL_ID
     *
     * @param jcflId the value for CHECKMIS.ST_GZXS_JCQKB.JCFL_ID
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setJcflId(Long jcflId) {
        this.jcflId = jcflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.ZT
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.ZT
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public Integer getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.ZT
     *
     * @param zt the value for CHECKMIS.ST_GZXS_JCQKB.ZT
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setZt(Integer zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.CREATEDATE
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.CREATEDATE
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.CREATEDATE
     *
     * @param createdate the value for CHECKMIS.ST_GZXS_JCQKB.CREATEDATE
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.MODIFYDATE
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.MODIFYDATE
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.MODIFYDATE
     *
     * @param modifydate the value for CHECKMIS.ST_GZXS_JCQKB.MODIFYDATE
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.CREATEUSER
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.CREATEUSER
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.CREATEUSER
     *
     * @param createuser the value for CHECKMIS.ST_GZXS_JCQKB.CREATEUSER
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.MODIFYUSER
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.MODIFYUSER
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public String getModifyuser() {
        return modifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.MODIFYUSER
     *
     * @param modifyuser the value for CHECKMIS.ST_GZXS_JCQKB.MODIFYUSER
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setModifyuser(String modifyuser) {
        this.modifyuser = modifyuser == null ? null : modifyuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECKMIS.ST_GZXS_JCQKB.JCFLMC
     *
     * @return the value of CHECKMIS.ST_GZXS_JCQKB.JCFLMC
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public String getJcflmc() {
        return jcflmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECKMIS.ST_GZXS_JCQKB.JCFLMC
     *
     * @param jcflmc the value for CHECKMIS.ST_GZXS_JCQKB.JCFLMC
     *
     * @mbg.generated Sat Nov 24 14:43:21 CST 2018
     */
    public void setJcflmc(String jcflmc) {
        this.jcflmc = jcflmc == null ? null : jcflmc.trim();
    }
}