package com.core.model.checkmis;

import com.core.pageModel.PageHelper;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GzrwExample extends PageHelper {
    /**
     * 数据库:CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * 数据库:CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * 数据库:CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public GzrwExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRwbhIsNull() {
            addCriterion("RWBH is null");
            return (Criteria) this;
        }

        public Criteria andRwbhIsNotNull() {
            addCriterion("RWBH is not null");
            return (Criteria) this;
        }

        public Criteria andRwbhEqualTo(String value) {
            addCriterion("RWBH =", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhNotEqualTo(String value) {
            addCriterion("RWBH <>", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhGreaterThan(String value) {
            addCriterion("RWBH >", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhGreaterThanOrEqualTo(String value) {
            addCriterion("RWBH >=", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhLessThan(String value) {
            addCriterion("RWBH <", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhLessThanOrEqualTo(String value) {
            addCriterion("RWBH <=", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhLike(String value) {
            addCriterion("RWBH like", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhNotLike(String value) {
            addCriterion("RWBH not like", value, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhIn(List<String> values) {
            addCriterion("RWBH in", values, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhNotIn(List<String> values) {
            addCriterion("RWBH not in", values, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhBetween(String value1, String value2) {
            addCriterion("RWBH between", value1, value2, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwbhNotBetween(String value1, String value2) {
            addCriterion("RWBH not between", value1, value2, "rwbh");
            return (Criteria) this;
        }

        public Criteria andRwmcIsNull() {
            addCriterion("RWMC is null");
            return (Criteria) this;
        }

        public Criteria andRwmcIsNotNull() {
            addCriterion("RWMC is not null");
            return (Criteria) this;
        }

        public Criteria andRwmcEqualTo(String value) {
            addCriterion("RWMC =", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcNotEqualTo(String value) {
            addCriterion("RWMC <>", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcGreaterThan(String value) {
            addCriterion("RWMC >", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcGreaterThanOrEqualTo(String value) {
            addCriterion("RWMC >=", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcLessThan(String value) {
            addCriterion("RWMC <", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcLessThanOrEqualTo(String value) {
            addCriterion("RWMC <=", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcLike(String value) {
            addCriterion("RWMC like", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcNotLike(String value) {
            addCriterion("RWMC not like", value, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcIn(List<String> values) {
            addCriterion("RWMC in", values, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcNotIn(List<String> values) {
            addCriterion("RWMC not in", values, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcBetween(String value1, String value2) {
            addCriterion("RWMC between", value1, value2, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwmcNotBetween(String value1, String value2) {
            addCriterion("RWMC not between", value1, value2, "rwmc");
            return (Criteria) this;
        }

        public Criteria andRwkssjIsNull() {
            addCriterion("RWKSSJ is null");
            return (Criteria) this;
        }

        public Criteria andRwkssjIsNotNull() {
            addCriterion("RWKSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRwkssjEqualTo(Date value) {
            addCriterion("RWKSSJ =", value, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjNotEqualTo(Date value) {
            addCriterion("RWKSSJ <>", value, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjGreaterThan(Date value) {
            addCriterion("RWKSSJ >", value, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjGreaterThanOrEqualTo(Date value) {
            addCriterion("RWKSSJ >=", value, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjLessThan(Date value) {
            addCriterion("RWKSSJ <", value, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjLessThanOrEqualTo(Date value) {
            addCriterion("RWKSSJ <=", value, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjIn(List<Date> values) {
            addCriterion("RWKSSJ in", values, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjNotIn(List<Date> values) {
            addCriterion("RWKSSJ not in", values, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjBetween(Date value1, Date value2) {
            addCriterion("RWKSSJ between", value1, value2, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwkssjNotBetween(Date value1, Date value2) {
            addCriterion("RWKSSJ not between", value1, value2, "rwkssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjIsNull() {
            addCriterion("RWJSSJ is null");
            return (Criteria) this;
        }

        public Criteria andRwjssjIsNotNull() {
            addCriterion("RWJSSJ is not null");
            return (Criteria) this;
        }

        public Criteria andRwjssjEqualTo(Date value) {
            addCriterion("RWJSSJ =", value, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjNotEqualTo(Date value) {
            addCriterion("RWJSSJ <>", value, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjGreaterThan(Date value) {
            addCriterion("RWJSSJ >", value, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjGreaterThanOrEqualTo(Date value) {
            addCriterion("RWJSSJ >=", value, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjLessThan(Date value) {
            addCriterion("RWJSSJ <", value, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjLessThanOrEqualTo(Date value) {
            addCriterion("RWJSSJ <=", value, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjIn(List<Date> values) {
            addCriterion("RWJSSJ in", values, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjNotIn(List<Date> values) {
            addCriterion("RWJSSJ not in", values, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjBetween(Date value1, Date value2) {
            addCriterion("RWJSSJ between", value1, value2, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andRwjssjNotBetween(Date value1, Date value2) {
            addCriterion("RWJSSJ not between", value1, value2, "rwjssj");
            return (Criteria) this;
        }

        public Criteria andZfsjIsNull() {
            addCriterion("ZFSJ is null");
            return (Criteria) this;
        }

        public Criteria andZfsjIsNotNull() {
            addCriterion("ZFSJ is not null");
            return (Criteria) this;
        }

        public Criteria andZfsjEqualTo(String value) {
            addCriterion("ZFSJ =", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjNotEqualTo(String value) {
            addCriterion("ZFSJ <>", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjGreaterThan(Date value) {
            addCriterion("ZFSJ >", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjGreaterThanOrEqualTo(String value) {
            addCriterion("ZFSJ >=", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjLessThan(Date value) {
            addCriterion("ZFSJ <", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjLessThanOrEqualTo(String value) {
            addCriterion("ZFSJ <=", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjLike(String value) {
            addCriterion("ZFSJ like", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjNotLike(String value) {
            addCriterion("ZFSJ not like", value, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjIn(List<String> values) {
            addCriterion("ZFSJ in", values, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjNotIn(List<String> values) {
            addCriterion("ZFSJ not in", values, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjBetween(String value1, String value2) {
            addCriterion("ZFSJ between", value1, value2, "zfsj");
            return (Criteria) this;
        }

        public Criteria andZfsjNotBetween(String value1, String value2) {
            addCriterion("ZFSJ not between", value1, value2, "zfsj");
            return (Criteria) this;
        }

        public Criteria andRwztIsNull() {
            addCriterion("RWZT is null");
            return (Criteria) this;
        }

        public Criteria andRwztIsNotNull() {
            addCriterion("RWZT is not null");
            return (Criteria) this;
        }

        public Criteria andRwztEqualTo(Short value) {
            addCriterion("RWZT =", value, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztNotEqualTo(Short value) {
            addCriterion("RWZT <>", value, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztGreaterThan(Short value) {
            addCriterion("RWZT >", value, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztGreaterThanOrEqualTo(Short value) {
            addCriterion("RWZT >=", value, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztLessThan(Short value) {
            addCriterion("RWZT <", value, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztLessThanOrEqualTo(Short value) {
            addCriterion("RWZT <=", value, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztIn(List<Short> values) {
            addCriterion("RWZT in", values, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztNotIn(List<Short> values) {
            addCriterion("RWZT not in", values, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztBetween(Short value1, Short value2) {
            addCriterion("RWZT between", value1, value2, "rwzt");
            return (Criteria) this;
        }

        public Criteria andRwztNotBetween(Short value1, Short value2) {
            addCriterion("RWZT not between", value1, value2, "rwzt");
            return (Criteria) this;
        }

        public Criteria andGzyqIsNull() {
            addCriterion("GZYQ is null");
            return (Criteria) this;
        }

        public Criteria andGzyqIsNotNull() {
            addCriterion("GZYQ is not null");
            return (Criteria) this;
        }

        public Criteria andGzyqEqualTo(String value) {
            addCriterion("GZYQ =", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqNotEqualTo(String value) {
            addCriterion("GZYQ <>", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqGreaterThan(String value) {
            addCriterion("GZYQ >", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqGreaterThanOrEqualTo(String value) {
            addCriterion("GZYQ >=", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqLessThan(String value) {
            addCriterion("GZYQ <", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqLessThanOrEqualTo(String value) {
            addCriterion("GZYQ <=", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqLike(String value) {
            addCriterion("GZYQ like", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqNotLike(String value) {
            addCriterion("GZYQ not like", value, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqIn(List<String> values) {
            addCriterion("GZYQ in", values, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqNotIn(List<String> values) {
            addCriterion("GZYQ not in", values, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqBetween(String value1, String value2) {
            addCriterion("GZYQ between", value1, value2, "gzyq");
            return (Criteria) this;
        }

        public Criteria andGzyqNotBetween(String value1, String value2) {
            addCriterion("GZYQ not between", value1, value2, "gzyq");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterion("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterion("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterion("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterion("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterion("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterion("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNull() {
            addCriterion("MODIFYUSER is null");
            return (Criteria) this;
        }

        public Criteria andModifyuserIsNotNull() {
            addCriterion("MODIFYUSER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyuserEqualTo(String value) {
            addCriterion("MODIFYUSER =", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotEqualTo(String value) {
            addCriterion("MODIFYUSER <>", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThan(String value) {
            addCriterion("MODIFYUSER >", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER >=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThan(String value) {
            addCriterion("MODIFYUSER <", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSER <=", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserLike(String value) {
            addCriterion("MODIFYUSER like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotLike(String value) {
            addCriterion("MODIFYUSER not like", value, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserIn(List<String> values) {
            addCriterion("MODIFYUSER in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotIn(List<String> values) {
            addCriterion("MODIFYUSER not in", values, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserBetween(String value1, String value2) {
            addCriterion("MODIFYUSER between", value1, value2, "modifyuser");
            return (Criteria) this;
        }

        public Criteria andModifyuserNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSER not between", value1, value2, "modifyuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHECKMIS.ST_GZRW
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}